root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "data", ".cache"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "html"]
  kill_delay = "0s"
  log = "build-errors.log"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
